name: todo-workflow

on:
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [22.x]
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      
      - name: setup nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}

      - name: clean install npm
        run: npm install

      - name: run build
        run: npm run build
      
      - name: run test
        run: npm run test



